### PR TITLE
Readme.md , lib and bin

### PR DESCRIPTION
**Pull request by xydinesh**
Did few minor changes to Readme file to show some formatting in github page and added lib and bin directories.

### CODE REVIEW

**Comment by xydinesh** [comment]
I'm not going to merge this pull request, you can review and merge it.

**Comment by bdsullivan** [comment]
Dinesh -  eb48bcf makes it look like you deleted the contents of README (the prior ones show you editing README.md which makes sense). Am I misunderstanding what it's telling me? We need to leave a README for use after download.

**Comment by xydinesh** [comment]
Yes, I replaced README with README.md with "git mv". I think, we can leave README.md to use after download.

**Comment by bdsullivan** [comment]
I'm just a little concerned about Windows users - .md is not a file format they're going to be familiar with (and we want them to open it in a txt editor).  No worries - I'll figure it out. Thanks for the clarification. 

Blair

-----Original Message-----

**Pull request merged**
